   apiVersion: v1
   kind: Service
   metadata:
     name: flyming-drone-backend-service
   spec:
     type: NodePort
     selector:
       app: flyming-drone-backend
     ports:
       - protocol: TCP
         port: 3000
         targetPort: 3000
         nodePort: 30001